#!/bin/bash
# v3.1

limit=10

if [ "$1" == "" ]; then								#proverka nalichiya username
 echo "Usage:" $0 "<username> <netadress> <mac-adress in any format> [i!]"
 exit 0
fi

qnamecount=`cat /etc/dhcpd.conf | grep -v ^# | awk '{print $2}' | grep -c ^$1$` #proverka unikalnosti username

if [ "$qnamecount" != "0" ]; then
 echo "ATTENTION: NAME IN USE"
 cat /etc/dhcpd.conf | grep $1
 exit 0
fi

if [ "$2" == "" ]; then								#proverka nalichiya netadress
   echo "Usage:" $0 " " $1 " <netadress> <mac-adress> [i]"
   exit 0
fi


qip=`echo $2 |awk -F. '{print $1"."$2"."$3}'`"\."


qipcount=`cat /etc/dhcpd.conf | grep -v ^# | awk '{print $5}' | grep -c $qip`	#proverka nalichiya ukazannoy podseti

if [ "$qipcount" == "0" ]; then
 echo "YOU SHOULD CREATE A SUBNETWORK OR ADD THE FIRST HOST"
 exit 0
fi

echo $qip

Llimit=`cat /etc/dhcpd.conf | grep range | grep $qip| awk '{print $2}'|awk -F. '{print $4}' `
Hlimit=`cat /etc/dhcpd.conf | grep range | grep $qip| awk '{print $3}'|awk -F. '{print $4}'|awk -F";" '{print $1}' `


list=`cat /etc/dhcpd.conf | grep -v ^"#" | awk '{print $5}'|grep $qip | awk -F. '{print $4}' | grep -v "^$"|awk -F\; '{print $1 | "sort -n" }'`


list=`echo -e "${list}\n${Llimit}\n${Hlimit}\n${limit}"|sort -n`

 qnextip=`echo $qip|awk -F'\' '{print $1}'`"."`echo "$list" | awk 'BEGIN {b=0;c=0}; 
   {if ((($1-b)>1)&&(b+1>=10)&&(b+1<l||b+1>h)) { if(c==0) c=b}; 
   b=$1};END {if (c==0) c=b; c++; print c}' l=$Llimit h=$Hlimit`

echo $qnextip


qtestip=`echo $qnextip | awk -F. '{print $4}'`
if [ "$qtestip" == "255" ]; then
echo "IP-adress not valid, select another network"
 exit 0
fi

if [ "$3" == "" ]; then
echo "Usage:" $0 " " $1 " " $2 "<mac-adress> [i]"
 exit 0
fi

tmp=`echo $3 | awk '{print length ($1) }'`
aster=` echo $3| grep -c "-" `

if [ "$tmp" == "12" ]; then

    qmac=`echo $3 | awk '{print substr($1, 1, 2)}'`":"`echo $3 \
     | awk '{print substr($1, 3, 2)}'`":"`echo $3\
     | awk '{print substr($1, 5, 2)}'`":"`echo $3 \
     | awk '{print substr($1, 7, 2)}'`":"`echo $3 \
     | awk '{print substr($1, 9, 2)}'`":"`echo $3 \
     | awk '{print substr($1, 11, 2)}'`
     
 elif [ "$tmp" == "17" ]; then
     
     if [ "$aster" != "0" ]; then
     
     qmac=`echo $3|awk 'gsub("-",":") {print}'`
     
     else qmac=$3
    
     fi
     
 else
     
     echo "Ivalid MAC-address"
     
fi
     
qmac=`echo $qmac| awk '{print tolower($1)'}`

qcount=`cat /etc/dhcpd.conf | grep -v ^# | grep -ic $qmac`

if [ "$qcount" != "0" ]; then
 echo ATTENTION: MAC ADRESS IN USE
 cat /etc/dhcpd.conf | grep -i $qmac
 exit 0
fi


  ip172=`echo $qip| awk -F. '{print $1"."$2}' `
  
if [ "$ip172" == "172.16" ]; then
  qip=$ip172
fi

echo `cat -n /etc/dhcpd.conf | grep -v ^# | grep host | grep $qip | awk '{print $1}' | tail -n 1`'a\' > /tmp/tmp.sed
echo "host "$1" {  fixed-address "$qnextip";  hardware ethernet "$qmac";}" >> /tmp/tmp.sed
sed -f /tmp/tmp.sed /etc/dhcpd.conf > /tmp/tmp.conf
cp /etc/dhcpd.conf /etc/dhcpconfs/dhcpd.`date +'%d%m%y%H%M'`
cp /tmp/tmp.conf /etc/dhcpd.conf
echo "DHCP USER ADDED Name: "$1" IP adress: "$qnextip
echo "host "$1" {  fixed-address "$qnextip";  hardware ethernet "$qmac";}" | mail -s "DHCP User added" dhcpadmin@nadrabank.kiev.ua
qfile=`date +'%y%m%d%H%M%S'`
echo $1" "$qnextip > /tmp/$qfile.add
cd /etc/init.d
./dhcpd restart

cd
rm /tmp/tmp.sed
rm /tmp/tmp.conf

